#!/usr/bin/env bash

echo "Hello, I am your test script running."
echo "Number of arguments I reveived: $#"
echo "Argument[0] (the program being run): $0"
echo "Argument[1]: $1" # This is empty if no arguments were passed
echo "Argument[2]: $2" # This is empty if only one argument was passed
echo "$(pwd)"

if [ ! -d "/tmp/$(basename $1)" ]; then
    mkdir /tmp/$(basename $1) 
fi

PROJ_TMP_DIR="/tmp/$(basename $1)"

git clone $1 $PROJ_TMP_DIR/$(git describe --always)

run-tests-bg $PROJ_TMP_DIR $(git describe --always) &

exit -1
