#!/bin/bash

if [[ ! -e /tmp/$(basename $1)/build.log ]]; then
   touch /tmp/$(basename $1)/build.log
   touch /tmp/$(basename $1)/build.fail

fi

make -C $1/$2 > /tmp/$(basename $1)/build.log 2> /tmp/$(basename $1)/build.fail 

if [[ $? -ne 0 ]]; then
    notify-send "Warning" "Build Has Failed"
    exit 1
fi

  
exit -1
