#!/usr/bin/env bash
#
echo "Hello, I am your test script running."

echo "Number of arguments I reveived: $#"
echo "Argument[0] (the program being run): $0"
echo "Argument[1]: $1" # This is empty if no arguments were passed
echo "Argument[2]: $2" # This is empty if only one argument was passed
echo "$(pwd)"

if [ ! -d "/tmp/$(basename $1)" ]; then
    mkdir /tmp/$(basename $1) 
fi

PROJ_TMP_DIR="/tmp/$(basename $1)"

git clone $1 $PROJ_TMP_DIR/$(git describe --always)

#TEST="2a6e909"

run-tests-bg $PROJ_TMP_DIR $(git describe --always) &


#sleep 10s && echo "It is annoying to wait for long commands to finish"
#sleep 10s & echo "We can put them in the background so we don't have to wait"
#notify-send "Test Message" "Blocking part of the script finished"
#echo "Notice that the second sleep is still running, we can tell by: $(pidof sleep)"

exit -1
