#!/bin/bash

if [[ ! -e /tmp/$(basename $1)/build.log ]]; then
   touch /tmp/$(basename $1)/build.log
   touch /tmp/$(basename $1)/build.fail

fi

make -C $1/$2 > /tmp/$(basename $1)/build.log 2> /tmp/$(basename $1)/build.fail 

if [[ $? -ne 0 ]]; then
    notify-send "Warning" "Build Has Failed"
    exit 1
fi

listTestFiles=$(find $1/$2 -name "*test*")

for file in $listTestFiles; do
    if [[ -x $file ]]; then
	regOutput="/tmp/$(basename $1)/$(basename $file)"Reg""
	errOutput="/tmp/$(basename $1)/$(basename $file)"Err""
	touch $regOutput
	touch $errOutput
        make -B $file > $regOutput 2> $errOutput
    fi
done

 
  
exit -1
